// Generated by CoffeeScript 1.3.3
(function() {

  define(function(require, exports, module) {
    var Component, editIt, editor, editorEl, linenum;
    editorEl = document.getElementById('editor');
    editIt = require('../lib/index');
    editor = editIt.edit(editorEl);
    Component = require('../lib/components/index');
    linenum = new Component('linenum');
    linenum._update = function(el, comps) {
      return el.text('1');
    };
    editor.comps.gutter.line(0, linenum);
    return {
      editorEl: editorEl,
      editor: editor,
      linenum: linenum
    };
  });

}).call(this);
