// Generated by CoffeeScript 1.3.3
(function() {

  define(function(require, exports, module) {
    var Editor;
    Editor = require('./components/editor');
    exports.edit = function(el) {
      return new Editor(el);
    };
    return exports;
  });

}).call(this);
