// Generated by CoffeeScript 1.3.3
(function() {

  define(function(require, exports, module) {
    var Editor;
    Editor = require('./components/editor');
    exports.edit = function(el) {
      var editor;
      editor = new Editor(el);
      editor.render();
      return editor;
    };
    return exports;
  });

}).call(this);
