// Generated by CoffeeScript 1.3.3
(function() {

  define(function(require, exports, module) {
    var to;
    exports.to = to = function(s) {
      return parseInt((s + '').replace(/\D/g, '')) || 0;
    };
    return exports;
  });

}).call(this);
