// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(function(require, exports, module) {
    var Component, Editor, Gutter, Layers, Time, utils;
    Component = require('./index');
    Gutter = require('./gutter');
    Layers = require('./layers');
    Time = require('./time');
    utils = {
      el: require('../utils/el')
    };
    require('../../jquery');
    Editor = (function(_super) {

      __extends(Editor, _super);

      function Editor() {
        return Editor.__super__.constructor.apply(this, arguments);
      }

      Editor.prototype._comps = function(comps) {
        comps.gutter = new Gutter;
        return comps.layers = new Layers;
      };

      Editor.prototype._update = function(el, comps) {
        el.append(comps.gutter.el);
        el.append(comps.layers.el);
        return el.append(new Date().toString());
      };

      return Editor;

    })(Component);
    return module.exports = Editor;
  });

}).call(this);
