// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(function(require, exports, module) {
    var Component, Gutter;
    Component = require('./index');
    require('../../jquery');
    Gutter = (function(_super) {

      __extends(Gutter, _super);

      function Gutter() {
        return Gutter.__super__.constructor.apply(this, arguments);
      }

      Gutter.prototype._update = function(el, comps) {
        var line, _i, _len, _ref, _results;
        _ref = comps.lines;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          line = _ref[_i];
          _results.push(el.append(line.el));
        }
        return _results;
      };

      Gutter.prototype._comps = function(comps) {
        return comps.lines = [];
      };

      Gutter.prototype.line = function(line, comp) {
        if (line < 0) {
          return this;
        }
        this.line(line - 1);
        if (comp instanceof Component || typeof comp.render === 'function') {
          this.comps.lines.push(this._registerComp(comp || this.comps.lines[line] || new Component));
        }
        return this;
      };

      return Gutter;

    })(Component);
    return module.exports = Gutter;
  });

}).call(this);
