// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(function(require, exports, module) {
    var Component, Layers;
    Component = require('./index');
    require('../../jquery');
    Layers = (function(_super) {

      __extends(Layers, _super);

      function Layers() {
        return Layers.__super__.constructor.apply(this, arguments);
      }

      Layers.prototype._comps = function(comps) {
        return comps.layers = this.layers = [];
      };

      Layers.prototype._update = function(el, comps) {
        return comps.layers.forEach(function(layer) {
          return el.append(layer.el);
        });
      };

      Layers.prototype.add = function(comp) {
        if (comp instanceof Component || typeof comp.render === 'function') {
          this.layers.push(this._registerComp(comp));
        }
        return this;
      };

      return Layers;

    })(Component);
    return module.exports = Layers;
  });

}).call(this);
