// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(function(require, exports, module) {
    var Component, Time;
    Component = require('./index');
    require('../../jquery');
    Time = (function(_super) {

      __extends(Time, _super);

      function Time() {
        Time.__super__.constructor.apply(this, arguments);
        this.tag = 'span';
        this.force = true;
      }

      Time.prototype._render = function(el, comps) {
        return el.text(new Date().toString());
      };

      return Time;

    })(Component);
    return module.exports = Time;
  });

}).call(this);
